### ISSUE TITLE
Hi Do you mind add the geo for the Texture blending example please?

### ISSUE THREAD

**Issue by vinyvince** [CorvaeOboro/zenv#1]
this one "propkit/pipe_10in/gen/ue4/pipe_10in_tee_flange.fbx"

cheers

**Comment by CorvaeOboro** [comment]
greetings , we created a new example ( hip\z_TEXTURE_SEAM_BLEND ) and updated the TEXTURE SEAM BLEND hda . some challenges encountered trying to update ,  more notes in the example , overall must use TGA's for the texture inputs and the hda needs to be unlocked to generate the mask and blended textures .
